### ISSUE TITLE
500 error when accessing /timesheet

### ISSUE THREAD

**Issue by vadim-ka** [Contargo/redmine-timesheet-plugin#12]
I'm getting 500 error when trying to access timesheet on fresh installed Redmine (no issues and no timelogs yet:

```
Started GET "/timesheet" for 86.57.161.11 at 2018-05-06 05:23:56 -0400
Processing by TimesheetsController#show as HTML
  Current user: vadim (id=1)
Completed 500 Internal Server Error in 26ms (ActiveRecord: 5.7ms)

NoMethodError (undefined method `sort_criteria' for nil:NilClass):
  plugins/timesheet/app/controllers/timesheets_controller.rb:20:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Installation details:

```
Environment:
  Redmine version                3.4.5.stable
  Ruby version                   2.4.4-p296 (2018-03-28) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
```

**Comment by sandra-thieme** [comment]
Hi,

this plugin currently only works with Redmine 3.3.X. See also https://github.com/Contargo/redmine-timesheet-plugin#redmine-compatible
