### ISSUE TITLE
NoMethodError (undefined method `sort_criteria' for nil:NilClass):

### ISSUE THREAD

**Issue by ghost** [Contargo/redmine-timesheet-plugin#10]
```
NoMethodError (undefined method `sort_criteria' for nil:NilClass):
  plugins/timesheet/app/controllers/timesheets_controller.rb:20:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
I'm trying to install this plugin, but when I go into it I get this error in the log / production.log. What am I doing wrong?
Debian 8.8
Redmine 3.4.2
Ruby 2.2.0
Rails 4.2.8

**Comment by jkn** [comment]
Exact same issue here.
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
Using timesheet source from Master branch.

**Comment by sandra-thieme** [comment]
Hi, as stated in the [README](https://github.com/Contargo/redmine-timesheet-plugin/blob/master/README.md#redmine-compatible) the plugin currently only works with Redmine 3.3.x.
