### ISSUE TITLE
500 error when trying access plugin

### ISSUE THREAD

**Issue by vadim-ka** [Contargo/redmine-timesheet-plugin#13]
Hello, I'm getting the following error when trying to access the plugin by /timesheet url:

```
Started GET "/timesheet" for 86.57.167.233 at 2018-08-08 10:11:12 +0100
Processing by TimesheetsController#show as HTML
  Current user: vadim (id=1)
Completed 500 Internal Server Error in 106ms (ActiveRecord: 13.0ms)

NoMethodError (undefined method `sort_criteria' for nil:NilClass):
  plugins/timesheet/app/controllers/timesheets_controller.rb:20:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Installation info:

```
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

Timesheet Plugin       0.70
```

**Comment by sandra-thieme** [comment]
Hi, unfortunately as of now the plugin only works with Redmine 3.3.x:

https://github.com/Contargo/redmine-timesheet-plugin#redmine-compatible

**Comment by vadim-ka** [comment]
Oops, sorry!
Thank you!
